<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[18]=array(0,1,1,'6K6h566X5py65LqM57qn');
$cfg_Cs[32]=array(0,1,1,'5LiJ57qn572R57uc5oqA5pyv');
$cfg_Cs[25]=array(0,1,1,'6KeG6aKR5a2m5Lmg');
$cfg_Cs[31]=array(0,1,0,'5Zyo57q/55WZ6KiA');
$cfg_Cs[27]=array(18,1,1,'5LqM57qnQ+ivreiogA==');
$cfg_Cs[28]=array(18,1,1,'5LqM57qnT2ZmaWNl');
$cfg_Cs[34]=array(25,1,1,'RXhjZWzmk43kvZzpopg=');
$cfg_Cs[35]=array(25,1,1,'UFBU5pON5L2c6aKY');
$cfg_Cs[36]=array(25,1,1,'V29yZOaTjeS9nOmimA==');
$cfg_Cs[37]=array(0,3,1,'6L2v5Lu25LiL6L29');
?>