<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",11,165);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",179,224);
$z[1][4]=array();
$z[1][4]['function']="MyDate('m-d',@me)";
$z[2]=Array("arcurl","",240,255);
$z[2][4]=array();
$z[3]=Array("title","",257,271);
$z[3][4]=array();

?>