<li><a href="[field:arcurl/]">[field:image/]<span class="title">[field:title/]</span></a></li>
       
       </ul>
      </div>
     </div>
    </dd>
   </dl>
  </div>
  <div id="leftAD1" style="margin:10px auto">{dede:mda name='700x90'/}</div>
  <!-- /picnews -->
  <div class="listbox"> {dede:channelartlist}
   <dl class="tbox">
    <dt><strong><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></strong><span class="more"><a href="{dede:field name='typeurl'/}">更多...</a></span></dt>
    <dd>
     <ul class="d1 ico3">
      {dede:arclist titlelen='60' row='8'}
      <li><span>[field:pubdate function="MyDate('m-d',@me)"/]</span><a href="[field:arcurl /]">[field:title /]</a></li>