<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?>
<!-- //底部模板 -->
<div class="footer w960 center mt1 clear">

    <div class="footer_left"></div>
    <div class="footer_body">
	<p class="powered">    
	<div class="copyright"><?php echo $GLOBALS['cfg_powerby']; ?>&nbsp;&nbsp;<?php echo $GLOBALS['cfg_beian']; ?></div></p>        
<!-- /powered -->
   </div>
   <div class="footer_right"></div>
</div>