<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><!-- //底部模板 -->
<div class="footer w960 center mt1 clear">
	<!-- 
			修改底部版权信息
	-->
    <div class="footer_left"></div>
    <div class="footer_body">
	<p class="powered">    
<div class="copyright">Copyright © 2016-2017 学考网 版权所有 &nbsp;&nbsp;<?php echo $GLOBALS['cfg_beian']; ?></div></p>        
<!-- /powered 
   </div>
   <div class="footer_right"></div>
   -->
</div>